// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Installment installment
//
// swagger:model Installment
type Installment struct {

	// due date
	// Required: true
	// Format: date
	DueDate *strfmt.Date `json:"dueDate"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// installment amount
	// Required: true
	InstallmentAmount *int64 `json:"installmentAmount"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this installment
func (m *Installment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDueDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstallmentAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Installment) validateDueDate(formats strfmt.Registry) error {

	if err := validate.Required("dueDate", "body", m.DueDate); err != nil {
		return err
	}

	if err := validate.FormatOf("dueDate", "body", "date", m.DueDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Installment) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Installment) validateInstallmentAmount(formats strfmt.Registry) error {

	if err := validate.Required("installmentAmount", "body", m.InstallmentAmount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this installment based on context it is used
func (m *Installment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Installment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Installment) UnmarshalBinary(b []byte) error {
	var res Installment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
